# Generated by Django 3.2.4 on 2021-07-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umasagar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
