# Generated by Django 3.2.5 on 2021-07-23 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umasagar', '0004_alter_salebill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='user',
            field=models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to='authentication.myuser'),
            preserve_default=False,
        ),
    ]
