# Generated by Django 3.2.5 on 2021-07-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umasagar', '0007_salebilldetails_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='remaining',
            field=models.IntegerField(default=1),
        ),
    ]
