# Generated by Django 3.2.5 on 2021-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umasagar', '0008_saleitem_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
