# Generated by Django 3.2.5 on 2021-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umasagar', '0009_alter_saleitem_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='despatched',
            field=models.IntegerField(default=0),
        ),
    ]
