# Generated by Django 3.2.5 on 2021-07-27 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umasagar', '0010_saleitem_despatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='order',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
