# Generated by Django 3.2.5 on 2021-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default='Address Here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='works_on',
            field=models.CharField(default='seeds', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='divison',
            name='divison',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mandal',
            name='mandal',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='usertype',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
